#ci cd
name: deploy nginx app
on:
  workflow_dispatch:

jobs:
  checkout:
    name: Git-checkout
    runs-on: nginx
    steps:
    - uses: actions/checkout@v4
  
  build-app:
    name: build nginx app
    needs: checkout
    runs-on: nginx
    steps:
      - name: docker build
        run: |
          ls -la
          docker build -t my-app:v1.0.0 .
          
  deploy-app:
    name: Deploy nginx app
    needs: build-app
    runs-on: nginx
    steps:
      - name: docker build
        run: |
          docker run --name mynginxapp -dit -P my-app:v1.0.0
          sleep 15
          docker ps -aq
